# Generated by Django 4.2.1 on 2024-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='reason',
            field=models.CharField(),
        ),
    ]
