# Generated by Django 4.2.1 on 2024-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_reports_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
