# Generated by Django 4.2.1 on 2024-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
