# Generated by Django 4.2.1 on 2024-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_review_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='manufacturer_company',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
