# Generated by Django 4.2.1 on 2024-11-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(default='user', max_length=12),
        ),
    ]
