# Generated by Django 4.2.1 on 2024-11-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=12),
        ),
    ]
